# Generated by Django 3.0.3 on 2020-06-14 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=20, verbose_name='last_name')),
                ('password', models.TextField(max_length=20, verbose_name='password')),
                ('email', models.TextField(max_length=50, verbose_name='email')),
                ('phone', models.IntegerField(verbose_name='phone')),
                ('type', models.IntegerField(verbose_name='type')),
            ],
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('capacity', models.IntegerField(verbose_name='capacity')),
                ('address', models.TextField(max_length=50, verbose_name='address')),
                ('phone', models.IntegerField(verbose_name='phone')),
                ('description', models.TextField(verbose_name='description')),
                ('video', models.TextField(verbose_name='video')),
                ('dj', models.TextField(verbose_name='dj')),
                ('flourist', models.TextField(verbose_name='flourist')),
                ('type', models.TextField(verbose_name='type')),
                ('separation', models.TextField(verbose_name='separation')),
                ('menu', models.TextField(verbose_name='menu')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.User')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField(verbose_name='capacity')),
                ('event', models.TextField(verbose_name='event')),
                ('videographer', models.TextField(verbose_name='videographer')),
                ('package', models.TextField(verbose_name='package')),
                ('menu', models.TextField(verbose_name='menu')),
                ('decor', models.TextField(verbose_name='decor')),
                ('separate', models.TextField(verbose_name='separate')),
                ('dj', models.TextField(verbose_name='dj')),
                ('date', models.TextField(verbose_name='date')),
                ('hall_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Hall')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.User')),
            ],
        ),
    ]
